"use client"
import Home from "./Components/Home";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function page() {
  return (
   <>
    <Home/>
   </>
  );
}
